# Generated by Django 2.2.6 on 2019-10-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, verbose_name='название программы')),
                ('program_text', models.TextField(verbose_name='текст программы')),
                ('pub_date', models.DateTimeField(verbose_name='дата')),
                ('img_stat', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.AlterModelOptions(
            name='my_img',
            options={'verbose_name': 'моё фото', 'verbose_name_plural': 'моё фото'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.RenameField(
            model_name='my_img',
            old_name='img_stat',
            new_name='my_img',
        ),
        migrations.AlterField(
            model_name='works',
            name='my_works',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
    ]
