# Generated by Django 2.2.6 on 2019-10-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191031_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программы', 'verbose_name_plural': 'Программы'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='img_stat',
        ),
    ]
