# Generated by Django 2.2.6 on 2019-10-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191031_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_name', models.CharField(max_length=200, verbose_name='приветствие')),
                ('hello_text', models.TextField(verbose_name='приветствие')),
            ],
            options={
                'verbose_name': 'приветствие',
                'verbose_name_plural': 'приветствие',
            },
        ),
    ]
