# Generated by Django 2.2.6 on 2019-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_name', models.CharField(max_length=200, verbose_name='приветствие')),
                ('hello_text', models.TextField(verbose_name='приветствие')),
                ('my_img', models.ImageField(null=True, upload_to='img', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'приветствие',
                'verbose_name_plural': 'приветствие',
            },
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='My_img',
        ),
    ]
