# Generated by Django 2.2.6 on 2019-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=200, verbose_name='название учебника')),
                ('linck_book', models.CharField(max_length=200, verbose_name='ссылка на учебник')),
                ('book_img', models.ImageField(null=True, upload_to='img', verbose_name='обложка')),
            ],
            options={
                'verbose_name': 'название учебника',
                'verbose_name_plural': 'название учебника',
            },
        ),
    ]
